### PR TITLE
New UI add ru localization

### PR DESCRIPTION
**Pull request by teuchezh**
maybe I did something wrong, tell me, I'll fix it

### CODE REVIEW

**Comment by teuchezh** [comment]
@olderzeus

**Comment by olderzeus** [comment]
Sorry that here Can't add ru direct, It's need a Cyrillic font file first.
1st: find a Cyrillic font file best fit 12pt height, may ttf or otf.
2nd: use fontfiles.py to process ttf or otf file generate the font file params
3rd: use ttf2img.py to convert a ttf ot otf file to a character bitmap file like NewUI/assets/font*.bmp
4th: direct edit bitmap file to optimization some character 
5th: use img2pyd.py convert a font bitmap file to font defined .h file to use.

Some scripts in tools you may can used and test.
Maybe forgotten something

**Comment by LeZerb** [comment]
I played around with a cyrillic font and the translation on my fork in branch [NewUI_add_ru_localization](https://github.com/LeZerb/game-and-watch-retro-go/tree/NewUI_add_ru_localization).

You could have a look there. Maybe you can get that into a pullable state. I did not yet have the time to finalize that.

**Comment by olderzeus** [comment]
Thanks for all, I'm glad to add Russian localization support

**Pull request merged**
